baseURL = 'https://noorix.com.au/'
languageCode = 'en-AU'
title = 'Noorix Awesome Tailwind Hugo Site'

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "/aboutus/"
    weight = 20

  [[menu.main]]
    name = 'Services'
    url = '/services'
    weight = 30

  [[menu.main]]
    name = 'Catering'
    url = '/services/catering'
    parent = 'Services'
    weight = 31
  
  [[menu.main]]
    name = 'Conferences'
    url = '/services/conferences'
    parent = 'Services'
    weight = 32

  [[menu.main]]
    name = 'Hospitality'
    url = '/services/hospitality'
    parent = 'Services'
    weight = 33

  [[menu.main]]
    name = 'Travel'
    url = '/services/travel'
    weight = 34
    parent = 'Services'

  [[menu.main]]
    name = "Contact Us"
    url = "/contactus/"
    weight = 40

  [[menu.main]]
    name = "Blogs"
    url = "/blog/"
    weight = 50

  
[params]
  author = "Blog Author"
  description = "This is an awesome Hugo Bootstrap site"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  categories = "categories"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.115.0"
[[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/alpinejs"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

